name: Build docs

on:
  # To trigger the workflow once you push to the `main` branch
  # Replace `main` with your branch’s name
  push:
    branches: ["main"]

  #To run the workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

env:
  PRODUCT: map_reduce_hw/m
  DOC_ARTIFACT: webHelpM2-all.zip

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Writerside docs using Docker
        uses: JetBrains/writerside-github-action@v3
      - name: Upload documentation
        uses: actions/upload-artifact@v3
        with:
          name: help
          path: artifacts/${{ env.DOC_ARTIFACT }}
          retention-days: 7

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Requires the build-job results
    needs: build-job
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: help
      - name: Unzip artifact
        uses: montudor/action-zip@v1
        with:
          args: unzip -qq ${{ env.DOC_ARTIFACT }} -d dir
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: dir
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1